-- Copyright 2010 Riccardo Belloli (belloli@email.it)
-- This file is a part of QDKP_V2 (see about.txt in the Addon's root folder)

--        ## ENGLISH-UNITED STATES (enUS) LOCALIZATION ##

--General
QDKP2_LOC_Net="Net"
QDKP2_LOC_Spent="Spent"
QDKP2_LOC_Total="Total"
QDKP2_LOC_Hours="Hours"
QDKP2_LOC_Start="Start"
QDKP2_LOC_Stop="Stop"
QDKP2_LOC_Finish="Finish"
QDKP2_LOC_Resume="Resume"
QDKP2_LOC_Session="Session"
QDKP2_LOC_GeneralSessName="General"


--Warnings/Questions
QDKP2_LOC_NotIntoAGuild="You are not into a Guild."
QDKP2_LOC_NotIntoARaid="You are not into a Raid."
QDKP2_LOC_NeedManagementMode="You need to start a session to be able to use that feature."
QDKP2_LOC_BetaWarning="You are running a beta version of QDKP2.\nShould you find a bug, please report it on\nthe addon's page at www.curse.com\nThanks!"
QDKP2_LOC_GoesNegative="$NAME's net DKP amount went negative."
QDKP2_LOC_Negative="$NAME's net DKP amount is negative."
QDKP2_LOC_ClearDB="Local database has been cleared."
QDKP2_LOC_Loaded=QDKP2_COLOR_RED.."$VERSION $BETA"..QDKP2_COLOR_WHITE.." Loaded"
QDKP2_LOC_NoRights=QDKP2_COLOR_RED.."You aren't allowed to do that."
QDKP2_LOC_EqToLowCap="Impossible to charge $NAME. His net DKP amount is equal to the minimum cap."
QDKP2_LOC_NearToLowCap="$NAME's Net DKP amount is too low. The maximum amount of DKP you can charge is $MAXCHARGE."
QDKP2_LOC_CloseSessionWithRaid="Do you want to close the ongoing session?\nIf you don't close it now, it will be\nautomatically closed in 5 minutes."
QDKP2_LOC_NameNotInGuild="$NAME doesn't seems to be in guild. Please try again in few seconds."
QDKP2_LOC_WinDetect_Q="Do you want to turn on the Winner\nDetect System?"
QDKP2_LOC_NoRevertOnCheck="You can't revert changes while a DKP values check is on the way. Wait for the check to complete and try again."
QDKP2_LOC_CloseSessNow="Do you want to close the current session\nas well?"
QDKP2_LOC_EnterRandTxt="Please enter a random text."
QDKP2_LOC_CantReadOfficerNotes="QDKP is set to read DKP data from officer notes, but your rank hasn't the right to view them. Either your guild or QDKP is misconfigured, tell your Guild Master about this issue."

--Raid Manager
QDKP2_LOC_IsInRaid="Is in the raid as the session starts"
QDKP2_LOC_IsInRaidOffline="Joins the session, offline"
QDKP2_LOC_JoinsRaid="Joins the Raid"
QDKP2_LOC_JoinsRaidSby="Joins the Raid as Standby"
QDKP2_LOC_JoinsActive="Joins the Raid as Active member"
QDKP2_LOC_GoesOnline="Returns Online"
QDKP2_LOC_GoesOffline="Goes Offline"
QDKP2_LOC_IsOffline="Is Offline"
QDKP2_LOC_NoInGuild="$NAMES don't seem to be in guild. Skipped"
QDKP2_LOC_LeftRaid="Leaves the Raid"
QDKP2_LOC_RemRaid="Removed from Raid Roster"
QDKP2_LOC_ExtJoins="$NAME has joined the active raid. Removed from standby list"

--IRONMAN BONUS
QDKP2_LOC_FinishWithRaid="The IronMan Bonus has not been closed yet.\nDo you want to close it now?"
QDKP2_LOC_StartButOffline="IronMan bonus has started but player is offline"
QDKP2_LOC_IronmanMarkPlaced="IronMan mark placed"
QDKP2_LOC_DataWiped="IronMan Data has been wiped"
QDKP2_LOC_No1Awarded="Nobody awarded the IronMan Bonus"
QDKP2_LOC_NumAwarded="$NUMBER players awarded $DKP DKP as IronMan Bonus"

--DKP Modify
QDKP2_LOC_Gains="Gains $GAIN DKP"
QDKP2_LOC_GainsSpends="Gains $GAIN and Spends $SPEND DKP"
QDKP2_LOC_GainsEarns="Gains $GAIN DKP and Earns $HOUR hours"
QDKP2_LOC_GainsSpendsEarns="Gains $GAIN and Spends $SPEND DKP, Earns $HOUR hours"
QDKP2_LOC_Spends="Spends $SPEND DKP"
QDKP2_LOC_SpendsEarns="Spends $SPEND DKP and Earns $HOUR hours"
QDKP2_LOC_Earns="Earns $HOUR hours"
QDKP2_LOC_ReceivedReas="Online Raid members received $AMOUNT DKP for $REASON"
QDKP2_LOC_Received="Raid members receive $AMOUNT DKP"
QDKP2_LOC_ZSRecReas="$NAME gives $AMOUNT DKP to the Raid for $REASON"
QDKP2_LOC_ZSRec="$NAME gives $AMOUNT DKP to the Raid"
QDKP2_LOC_RaidAw="[Raid Award] $AWARDSPENDTEXT"
QDKP2_LOC_RaidAwReas="[Raid Award] $AWARDSPENDTEXT for $REASON"
QDKP2_LOC_RaidAwMain="RAID $AWARDSPENDTEXT"
QDKP2_LOC_RaidAwMainReas="RAID $AWARDSPENDTEXT for $REASON"
QDKP2_LOC_ZeroSumSp="Gives $SPENT DKP to the Raid"
QDKP2_LOC_ZeroSumSpReas="Gives $SPENT DKP to the Raid for $REASON"
QDKP2_LOC_ZeroSumAw="Gets $AMOUNT DKP from $GIVER"
QDKP2_LOC_ZeroSumAwReas="Gets $AMOUNT DKP from $GIVER for $REASON"
QDKP2_LOC_ExtMod="$AWARDSPENDTEXT for external editing"
QDKP2_LOC_Generic="$AWARDSPENDTEXT" --these are used in the general case. (eg. manual editing to DKP)
QDKP2_LOC_GenericReas="$AWARDSPENDTEXT for $REASON"
QDKP2_LOC_DKPPurchase="Purchases $ITEM for $AMOUNT DKP"
QDKP2_LOC_NoPlayerInChance="You are trying to modify a player that doesn't exist in local cache"
QDKP2_LOC_MaxNetLimit="$NAME's DKP gain has been limitated because he reached the Maximum Net DKP Cap ($MAXIMUMNET)"
QDKP2_LOC_MaxNetLimitLog="Maximum net DKP cap reached. Gain has been adjusted"
QDKP2_LOC_MinNetLimit="$NAME's DKP loss has been limitated because he reached the Minimum Net DKP Cap ($MINIMUMNET)"
QDKP2_LOC_MinNetLimitLog="Minimum net DKP cap reached. Loss has been adjusted"

--lost awards
QDKP2_LOC_NODKP_Offline="Offline"
QDKP2_LOC_NODKP_Rank="No-DKP Rank"
QDKP2_LOC_NODKP_Zone="Out of Zone"
QDKP2_LOC_NODKP_Manual="Manually excluded"
QDKP2_LOC_NODKP_Generic="Generic reason"
QDKP2_LOC_NODKP_LowAtt="Low attendance($PERC%%)"
QDKP2_LOC_NODKP_NetLimit="Net DKP Limit"
QDKP2_LOC_NODKP_IMStart="Not in at IronMan start"
QDKP2_LOC_NODKP_IMStop="Not in at IronMan stop"
QDKP2_LOC_NoDKPRaid="$WHYNOT. Loses Raid award of $AMOUNT DKP"
QDKP2_LOC_NoDKPRaidReas="$WHYNOT. Loses Raid award of $AMOUNT DKP for $REASON"
QDKP2_LOC_NoDKPZS="$WHYNOT. Loses ZS share of $AMOUNT DKP from $GIVER"
QDKP2_LOC_NoDKPZSReas="$WHYNOT. Loses ZS share of $AMOUNT DKP for $REASON"
QDKP2_LOC_NoTick="$WHYNOT. Loses Timer Tick"

--timer
QDKP2_LOC_TimerTick="Timer Tick"
QDKP2_LOC_IntegerTime="Hourly Bonus"
QDKP2_LOC_RaidTimerLog="Timer Tick. Online Raid members award $TIME hours"
QDKP2_LOC_TimerStop="Timer stopped"
QDKP2_LOC_TimerResumed="Timer resumed"
QDKP2_LOC_TimerStarted="Timer started"
QDKP2_LOC_TimerPaused="Timer paused"
QDKP2_LOC_GUItimer="%M:%S to tick"

--upload
QDKP2_LOC_NoMod="No DKP modifications have been done since last download/upload"
QDKP2_LOC_SucLocal="Upload Report: $UPLOADED external entries stored in RAM."
QDKP2_LOC_Successful="Upload report: $UPLOADED notes sent. Wait for check..."
QDKP2_LOC_Failed="Upload report: $FAILED haven't been successfull uploaded. Try again in few seconds"
QDKP2_LOC_IndexNoFound="$NAME's guild index cannot be found, skipped. Will try again in a minute"
QDKP2_LOC_IndexNoFoundLog="Has a broken guild cache index (Upload Failed)"
QDKP2_LOC_CheckOK="CHECK: DKP are syncronized."
QDKP2_LOC_CheckAborted="Upload Check aborted due to modifications done"

--Externals
QDKP2_LOC_CantAddExternalInGuild="Can't add $NAME as esternal: he is already in guild."
QDKP2_LOC_CantDeleteUnexistingExternals="Can't delete $NAME: he's not a valid external."
QDKP2_LOC_InvalidExternalName="Invalid name for an external."
QDKP2_LOC_ExternalRemoved="$NAME has been removed from Guild Roster as External."
QDKP2_LOC_ExtPost="<QDKP2> External's DKP Amounts"
QDKP2_LOC_ExtLine="$NAME: Net=$NET, Total=$TOTAL, Hours=$HOURS"

--Bid manager
QDKP2_LOC_BidAck = "OK, bet received."
QDKP2_LOC_CantRebid = "You already placed a bet for this bidding."
QDKP2_LOC_BidEqual = "Your bet is the same to the previous one."
QDKP2_LOC_BidLess = "Your bet is less than the previous one."
QDKP2_LOC_BidGreater = "You can't bid more DKP than you have. The maximum bid you can place is $NET."
QDKP2_LOC_BidnoDKP = "You need at least $MINBID DKP to place a bid. You have $NET."
QDKP2_LOC_BidNoGuild = "Only GuildMembers are allowed to bid."
QDKP2_LOC_BidLessMinimum = "The minimum bid is $MINBID"
QDKP2_LOC_BidMoreMaximum = "The maximum bid is $MAXBID"
QDKP2_LOC_BidRollWrong = "That wasn't a standard 1-100 roll."
QDKP2_LOC_BidRollMulti = "You can't roll twice."
QDKP2_LOC_BidRollFirstv = "You must /roll before placing that bid."
QDKP2_LOC_BidRollAck = "OK, roll acquired."
QDKP2_LOC_BidRemove = "Your bet has been removed."
QDKP2_LOC_BidPlaceLog = 'Bets for $ITEM: "$BIDTEXT"'
QDKP2_LOC_BidPlaceLogVal = "($VALUE)"
QDKP2_LOC_BidRemovedLog = "Last bet has been cancelled."
QDKP2_LOC_BidRollsLog = "Rolls $ROLL for $ITEM"
QDKP2_LOC_BidStartLog = "Bidding started for $ITEM."
QDKP2_LOC_BidWinLog = "Wins the bidding for $ITEM."
QDKP2_LOC_BidCancelLog = "Bidding for $ITEM has been cancelled."
QDKP2_LOC_NoEligible = "You are not eligible to use that keyword."

--Log
QDKP2_LOC_GeneralSession="General"
QDKP2_LOC_NoSessName="No name"
QDKP2_LOC_LootsItem="Loots $ITEM"
QDKP2_LOC_ShardsItem="Shards $ITEM"
QDKP2_LOC_BossKill="$BOSS has been slain!"
QDKP2_LOC_Kill="$BOSS kill" -- used as reason for boss DKP awards.
QDKP2_LOC_InvalidLog="*INVALID: Unknown log type*"
QDKP2_LOC_InvalidLogDKP="*INVALID: Corrupted DKP entry (no UnDo field)*"
QDKP2_LOC_InvalidLinkTime="*INVALID LINK: No timestamp*"
QDKP2_LOC_InvalidLinkPlayer="*INVALID LINK: No linked player*"
QDKP2_LOC_InvalidLinkSession="*INVALID LINK: No linked session*"
QDKP2_LOC_InvalidLinkSessName="*INVALID LINK: Linked session does not exists.*"
QDKP2_LOC_JoinSess="Joins session $NAME"
QDKP2_LOC_SessJoin="Takes part at session $SESSION"

--download
QDKP2_LOC_NewSessionQ="Enter the name of the New Session"
QDKP2_LOC_NewSession="New Session Started: $SESSIONNAME"
QDKP2_LOC_DifferentTot="$NAME's net+spent is different from the total. Please check"
QDKP2_LOC_NewGuildMember="$NAME added to the Guild Roster as new Member."
QDKP2_LOC_ExternalJoined="$NAME becamed a Guild Member. I'm removing the external record, please upload changes as soon as possible."
QDKP2_LOC_GuildRosterReverted="All guild unuploaded changes have been reverted back to notes values."
QDKP2_LOC_AddedToGuildRoster="Added $NUM players to the guild roster."
QDKP2_LOC_CloseIMSessWarn="The IronMan bonus has not been finalized.\nIf you close the session the IronMan\nbonus will be discarded.\nYou still want to halt the session?"
